#version 450

layout(std430, binding = 0) buffer InData1 
{
	uint inData1[];
};

layout(std430, binding = 1) readonly buffer InData2 
{
	uint inData2[];
};

layout(push_constant, std430) uniform pc 
{
	uint dataLength;
};

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx > pc.dataLength){return}
	
	inData1[idx] += inData2[idx];
}
